version: "3.9"


services:

  api:
    build:
      context: .
      target: api
    container_name: "api"
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    networks:
      - postgres_network
    depends_on:
      - postgres
    restart: always
    env_file: ".env"

  tg-bot:
    build:
      context: .
      target: tg-bot
    container_name: "tg-bot"
    environment:
      TG_BOT_TOKEN: "${TG_BOT_TOKEN}"
    restart: always
    env_file: ".env"


  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - postgres_network
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      PGPORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    env_file: ".env"
    restart: always

networks:
  postgres_network:

volumes:
  postgres_data: