version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: %{DB_USER}
      POSTGRES_DB: %{DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_postgres_network:

volumes:
  postgres_data: