name: Deploy to Server

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print DEV_SERVER_URL
        run: echo "$DEV_SERVER_URL"
        env:
          DEV_SERVER_URL: ${{ secrets.DEV_SERVER_URL }}
          
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DEV_SERVER_URL >> ~/.ssh/known_hosts
        env:
          DEV_SERVER_URL: ${{ secrets.DEV_SERVER_URL }}

      - name: Sync repo to host
        run: |
          echo "$DEV_ENV_FILE" > .env
          echo "CI_COMMIT_BRANCH=${GITHUB_REF##*/}" >> .env
          ssh -o StrictHostKeyChecking=no $DEV_USER_NAME@$DEV_SERVER_URL -p $DEV_SERVER_PORT "mkdir -p $DEV_BASE_DIR"
          ssh -o StrictHostKeyChecking=no $DEV_USER_NAME@$DEV_SERVER_URL -p $DEV_SERVER_PORT "apt-get update && apt-get install -y rsync"
          rsync -zvrRth --progress --no-inc-recursive --exclude '.git' . $DEV_USER_NAME@$DEV_SERVER_URL:$DEV_BASE_DIR
        env:
          DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
          DEV_SERVER_PORT: ${{ secrets.DEV_SERVER_PORT }}
          DEV_SERVER_URL: ${{ secrets.DEV_SERVER_URL }}
          DEV_BASE_DIR: ${{ secrets.DEV_BASE_DIR }}
          DEV_USER_NAME: ${{ secrets.DEV_USER_NAME }}
          DEV_SERVER_PASSWORD: ${{ secrets.DEV_SERVER_PASSWORD }}

  deploy:
    runs-on: self-hosted
    environment: default_env
    needs: sync

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Launch containers
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no $USER_NAME@$SERVER_URL -p $SERVER_PORT "cd $BASE_DIR && docker compose --env-file .env up --build -d"

      - name: Docker system prune
        if: ${{ env.NOT_PRUNE_DOCKER != 'true' }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no $USER_NAME@$SERVER_URL -p $SERVER_PORT "docker system prune --all --force"
        env:
          NOT_PRUNE_DOCKER: ${{ secrets.NOT_PRUNE_DOCKER }}
